apiVersion: v1
kind: Pod
metadata:
  name: app-with-sidecar
  labels:
    app.kubernetes.io/name: app-with-sidecar
    nginx.kyverno.io/inject: "true"
spec:
  containers:
    - name: app-with-sidecar
      image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/app-with-sidecar:latest
      imagePullPolicy: IfNotPresent