---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr-image-checker
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ecr-image-checker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ecr-image-checker
    spec:
      containers:
        - name: ecr-image-checker
          image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/ecr-image-checker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: ecr-image-checker
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: ecr-image-checker
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898