repositories:
  - name: kyverno
    url: https://kyverno.github.io/kyverno/

releases:
  - name: kyverno
    namespace: kyverno
    chart: kyverno/kyverno
    version: 3.2.6
    createNamespace: true
    wait: true
    # values:
    #   # You can add custom values here if needed
    #   replicaCount: 1
    
    # hooks:
    #   - events: ["presync"]
    #     showlogs: true
    #     command: "kubectl"
    #     args:
    #       - create
    #       - namespace
    #       - kyverno