repositories:
  - name: kyverno
    url: https://kyverno.github.io/kyverno/
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.15.3
    createNamespace: true
    wait: true
    values:
      - crds:
          enabled: true

  - name: kyverno
    namespace: kyverno
    chart: kyverno/kyverno
    version: 3.2.6
    createNamespace: true
    wait: true
    values:
      - admissionController:
          rbac:
            clusterRole:
              extraResources:
                - apiGroups:
                  - 'keda.sh'
                  resources:
                  - scaledjobs
                  - scaledobjects
                  verbs:
                    - create
                    - update
                    - delete
                    - patch
                - apiGroups:
                  - 'cert-manager.io'
                  resources:
                  - certificates
                  verbs:
                    - create
                    - update
                    - delete
                    - patch
                    
        backgroundController:
          rbac:
            clusterRole:
              extraResources:
                - apiGroups:
                  - 'keda.sh'
                  resources:
                  - scaledjobs
                  - scaledobjects
                  verbs:
                    - create
                    - update
                    - delete
                    - patch
                - apiGroups:
                  - 'cert-manager.io'
                  resources:
                  - certificates
                  verbs:
                    - create
                    - update
                    - delete
                    - patch